@token = -F93r1Ty6D7_b7-jnr8BJDHmcpYAGDQ
POST https://www.reddit.com/api/v1/access_token
Authorization: Basic aXFCaUw2MEV6OUxlZlE6Cg==

grant_type=https://oauth.reddit.com/grants/installed_client&device_id=DO_NOT_TRACK_THIS_DEVICE

###

GET https://oauth.reddit.com/hot?limit=1
User-Agent: rippit
Authorization: Bearer {{token}}